[[Libxc_GPU]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "94bd3c8b78794afceab749a3d351a5b438324c17"
lazy = true
libc = "glibc"
os = "linux"

    [[Libxc_GPU.download]]
    sha256 = "62d262c826dbd1f08529fb87330d5c015796562ea7ed56ac8ee89da58d353874"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_GPU_jll.jl/releases/download/Libxc_GPU-v6.1.0+1/Libxc_GPU.v6.1.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
